source 'https://rubygems.org'

# gem 'yaml'
gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'page-object', '~> 2.0'
gem 'data_magic'
gem 'report_builder'
gem 'rest-client'
gem 'savon'
gem 'gmail'
gem 'watir-scroll'
gem 'appium_lib'
gem 'watir-webdriver'
gem 'selenium-webdriver'
gem 'win32-clipboard', '~> 0.6.4'
gem 'rubyXL'